# Generated by Django 5.2.4 on 2025-07-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_profile_pix_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
