# Generated by Django 5.2.4 on 2025-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
