# Generated by Django 5.2.4 on 2025-07-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_modelname_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='Product',
        ),
    ]
