# Generated by Django 5.2.4 on 2025-08-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_category_created_category_image_category_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='Cart',
            new_name='cart',
        ),
    ]
