# Generated by Django 5.2.4 on 2025-08-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_cart_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
