# Generated by Django 5.2.4 on 2025-08-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_cartproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='price',
        ),
    ]
